baseurl: "/"
paginate_path: "/page:num"
paginate: 10
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-youtube

url: # Your complete URL https://your.domain.om
sitename: # Your Site-Namae
imglogopath: # Path To Logo-Image
faviconpath: # Path To Favicon
cookiealert:
appletouchiconpath: # Path To Apple-Touch Favicon
author: # Will be displayed at every post as the post-author
htmlheadstart:
htmlbeforeheadend: site-htmlbeforeheadend.html
htmlbodystart:
htmlbeforebodyend:
